name: Read Config

on:
  workflow_call:
    outputs:
      config: 
        description: "The configuration as a JSON string"
        value: ${{ jobs.set-environment-variables.outputs.config }}

jobs:
  set-environment-variables:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.read-config.outputs.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        
      - name: Read config
        id: read-config
        run: |
          echo "Reading config file..."
          config=$(cat ./.github/config.yml | yq eval -o=json)
          echo "config=$config" >> $GITHUB_OUTPUT
          echo "Config: $config"  # Debug output
        
      - name: Show Config
        run: echo "${{ steps.read-config.outputs.config }}"