name: Read Configuration

on:
  workflow_call:
    outputs:
      CONFIG:
        description: "The configuration file as key-value pairs"
        value: ${{ jobs.read-config.outputs.CONFIG }}

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      CONFIG: ${{ steps.set-config.outputs.CONFIG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Read Configuration and set outputs
        id: set-config
        run: |
          echo "CONFIG=$(cat .github/config.txt)" >> $GITHUB_OUTPUT
