name: Read Configuration

on:
  workflow_call:
    outputs:
        CONFIG:
            description: "The configuration file as key-value pairs"
            value: ${{ jobs.read-config.steps.set-config.outputs.CONFIG }}

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - name: Read Configuration and set outputs
        id: set-config
        run: |
            echo "CONFIG=$(cat ./.github/config.yml)" >> $GITHUB_OUTPUT