name: Read Configuration

on:
  workflow_call:

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Read Configuration
        run: |
          while IFS= read -r line; do
            key=$(echo "$line" | cut -d ' ' -f 1)
            value=$(echo "$line" | cut -d ' ' -f 2-)
            echo "::set-output name=${key}::${value}"
          done < config.txt