name: Read Config

on:
  workflow_call:
    outputs:
      config:
        description: "All config variables"
        value: ${{ jobs.steps.set-output.outputs.config }}

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Read YAML and set output
        id: set-output
        run: |
          CONFIG=$(yq e 'to_entries | map(.key + "=" + .value | gsub("\""; "")) | join(",")' ./.github/config.yml)
          echo "config=${CONFIG}" >> $GITHUB_OUTPUT