name: Read Config

on:
    workflow_call:
        outputs:
            config:
                description: "JSON string containing all config values"
                value: ${{ jobs.set-environment-variables.outputs.config }}

jobs:
    set-environment-variables:
        runs-on: ubuntu-latest
        outputs:
            config: ${{ steps.set_vars.outputs.config }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7
            - name: Read all config values and set them as outputs
              id: set_vars
              run: |
                # Read the YAML file and convert it to JSON
                CONFIG_JSON=$(yq eval -o=json config.yml)
                # Escape the JSON string to handle multiline output
                CONFIG_JSON_ESCAPED="${CONFIG_JSON//'%'/'%25'}"
                CONFIG_JSON_ESCAPED="${CONFIG_JSON_ESCAPED//$'\n'/'%0A'}"
                CONFIG_JSON_ESCAPED="${CONFIG_JSON_ESCAPED//$'\r'/'%0D'}"
                # Set the entire config as a single output
                echo "config=${CONFIG_JSON_ESCAPED}" >> $GITHUB_OUTPUT