name: Read Configuration

on:
  workflow_call:
    outputs:
      FLUTTER_VERSION:
        description: "Flutter version"
        value: '3.24.3'
      JAVA_VERSION:
        description: "Java version"
        value: '17'
      JAVA_DISTRIBUTION:
        description: "Java distribution"
        value: 'oracle'

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7
        - name: Report
          run: echo "Read configuration"
        - name: Create a file
          run: |
            echo "Hello World 123!" >> test.txt
            echo "read-config workflow created test.txt with content $(cat test.txt)"
            pwd
            ls