name: Read Configuration

on:
  workflow_dispatch:
  push:
    paths:
      - 'config.txt'

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read Configuration
        env:
          CONFIG: $(cat config.txt)
        run: |
          # Access configuration values directly using $CONFIG environment variable
          IFS= read -r -d '' line
          while [[ -n "$line" ]]; do
            key=$(echo "$line" | cut -d ' ' -f 1)
            value=$(echo "$line" | cut -d ' ' -f 2-)
            echo "::set-env name=${key}::${value}"
            read -r -d '' line
          done < <(echo "$CONFIG")