name: Read Config

on:
  workflow_call:
    outputs:
      config:
        description: "All config variables"
        value: ${{ steps.set-output.outputs.config }}

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Read YAML and set output
        id: set-output
        run: |
          echo "config<<EOF" >> $GITHUB_OUTPUT
          yq e 'to_entries | map(.key + "=" + .value | gsub("\""; "")) | .[]' ./.github/config.yml >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT