name: Read Configuration

on:
  workflow_call:
    outputs:
      FLUTTER_VERSION:
        description: "Flutter version"
        value: '3.24.3'
      JAVA_VERSION:
        description: "Java version"
        value: '17'
      JAVA_DISTRIBUTION:
        description: "Java distribution"
        value: 'oracle'

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
        - name: Report
          run: echo "Read configuration"