name: Read Configuration

on:
  workflow_call:

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - name: Read Configuration and set outputs
        id: set-config
        run: |
            echo "CONFIG=$(cat .github/config.txt)" >> $GITHUB_ENV