name: Read Config

on:
  workflow_call:

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Read YAML and set environment variables
        run: |
          while IFS='=' read -r key value; do
            echo "${key}=${value}" >> $GITHUB_ENV
          done < <(sed 's/: /=/g' ./.github/config.yml)

      - name: Debug Output
        run: |
          echo "Environment variables set:"
          env | grep -E "FLUTTER_VERSION|JAVA_VERSION|JAVA_DISTRIBUTION|myName"