name: Read Configuration

on:
  workflow_call:

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      CONFIG: ${{ steps.set-config.outputs.config }}
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Read Configuration and set as output
        id: set-config
        run: |
          # Read configuration values from config.txt and output them
          CONFIG=$(cat ./.github/config.txt)

          # Output CONFIG variable (single string with newline replaced by spaces)
          echo "::set-output name=config::$(echo $CONFIG | tr '\n' ' ')"