name: Read Configuration

on:
  workflow_call:

jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Read Configuration
        run: |
          # Access the configuration values directly
          CONFIG=$(cat config.txt)

          # Read line by line and set environment variables using GITHUB_ENV
          while IFS= read -r line || [ -n "$line" ]; do
            key=$(echo "$line" | cut -d ' ' -f 1)
            value=$(echo "$line" | cut -d ' ' -f 2-)
            echo "${key}=${value}" >> $GITHUB_ENV
          done <<< "$CONFIG"