on:
  workflow_dispatch:
  push:
    branches:
      - main
name: "Test, Build & Release Android"

jobs:
  build:
    permissions: write-all
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            hello
      - run: cat hello
      - run: echo ${{github.run_number}}
      - run: cat pubspec.yaml
      # Get version from pubspec.yaml version is of form: version: 100.9.0+101
      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(awk '/^version:/ {print $2}' pubspec.yaml)"
      - run: echo ${{ steps.get_version.outputs.version }}
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "hello"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v-${{ steps.get_version.outputs.version }}
          removeArtifacts: true