on:
  workflow_dispatch:
  push:
    branches:
      - dev
name: "Test, Build & Release Android"

jobs:
  build:
    permissions: write-all
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            hello
      - name: Create Tag
        id: create_tag
        run: echo ::set-output name=TAG::$(echo ${GITHUB_REF#refs/tags/})
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "hello"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.create_tag.outputs.TAG }}
