on:
  workflow_dispatch:
  push:
    branches:
      - main
name: "Test, Build & Release Android"

jobs:
  build:
    permissions: write-all
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            hello
      - run: cat hello
      - run: echo ${{github.run_number}}
      - run: cat pubspec.yaml
      # Get version from pubspec.yaml version is of form: version: 100.9.0 and append to it +${{github.run_number}}
      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(cat pubspec.yaml | grep version | cut -d' ' -f2)+${{github.run_number}}"
      # change the version in build.gradle to match the version in pubspec.yaml
      - name: Set version in build.gradle
        # in build.gradle, it is of the form:
        # def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
        #if (flutterVersionCode == null) {
        #    flutterVersionCode = '1'
        #}
        #
        #def flutterVersionName = localProperties.getProperty('flutter.versionName')
        #if (flutterVersionName == null) {
        #    flutterVersionName = '1.0'
        #}
        # ...
        #    defaultConfig {
        #        ...
        #        targetSdkVersion flutter.targetSdkVersion
        #        versionCode flutterVersionCode.toInteger()
        #        versionName flutterVersionName
        #    }
        run: |
          sed -i '' "s/def flutterVersionCode = localProperties.getProperty('flutter.versionCode')/def flutterVersionCode = '${{ steps.get_version.outputs.version }}'/g" android/app/build.gradle
          sed -i '' "s/def flutterVersionName = localProperties.getProperty('flutter.versionName')/def flutterVersionName = '${{ steps.get_version.outputs.version }}'/g" android/app/build.gradle
          cat android/app/build.gradle
      - run: cat android/app/build.gradle
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "hello"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.get_version.outputs.version }}
          removeArtifacts: true