on:
  workflow_dispatch:
  push:
    branches:
      - main
name: "Test, Build & Release Android"

jobs:
  build:
    permissions: write-all
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            hello
      - run: cat hello
      - run: echo ${{github.run_number}}
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "hello"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.0+${{github.run_number}}
          allowUpdates: true