name: Workflow 1

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  read-config:
    uses: ./.github/workflows/read-config.yml

  first-job:
    name: First Job
    runs-on: ubuntu-latest
    needs: read-config

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Use Config Variables
        run: |
            echo "fv = ${{ needs.read-config.outputs.FLUTTER_VERSION }}"
            echo "jv = ${{ needs.read-config.outputs.JAVA_VERSION }}"