name: Workflow 1

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  read-config:
    uses: ./.github/workflows/read-config.yml

  first-job:
    name: First Job
    runs-on: ubuntu-latest
    needs: read-config

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Use Config Variables
        run: |
          echo "Flutter version: ${{ needs.read-config.outputs.FLUTTER_VERSION }}"
          echo "Java version: ${{ needs.read-config.outputs.JAVA_VERSION }}"
          echo "Java distribution: ${{ needs.read-config.outputs.JAVA_DISTRIBUTION }}"
          echo "My name: ${{ needs.read-config.outputs.myName }}"
          echo "His name: ${{ needs.read-config.outputs.hisName }}"
          echo "Her name: ${{ needs.read-config.outputs.herName }}"