name: Workflow 1

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
    first-job:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7
            
            - name: Call config workflow
              uses: ./.github/workflows/read-config.yml
              id: config

            - name: Display all config vars
              run: |
                echo 'Config values:'
                echo '${{ steps.config.outputs.config }}' | jq -r 'to_entries[] | "\(.key): \(.value)"'

            - name: Use specific config values (example)
              run: |
                CONFIG='${{ steps.config.outputs.config }}'
                FLUTTER_VERSION=$(echo $CONFIG | jq -r '.FLUTTER_VERSION')
                MY_NAME=$(echo $CONFIG | jq -r '.myName')
                echo "Flutter Version: $FLUTTER_VERSION"
                echo "My Name: $MY_NAME"