name: Workflow 1

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  read-config:
    uses: ./.github/workflows/read-config.yml

  first-job:
    name: First Job
    runs-on: ubuntu-latest
    needs: read-config
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        
      - name: Set environment variables
        run: |
          IFS=',' read -ra CONFIG <<< "${{ needs.read-config.outputs.config }}"
          for item in "${CONFIG[@]}"; do
            echo "$item" >> $GITHUB_ENV
          done
        
      - name: Say Hi
        run: echo "Hi, I am the first step in the first job of the first workflow."
      
      - name: Use Config Variables
        run: |
          echo "Flutter version: ${{ env.FLUTTER_VERSION }}"
          echo "Java version: ${{ env.JAVA_VERSION }}"
          echo "Java distribution: ${{ env.JAVA_DISTRIBUTION }}"
          echo "My name: ${{ env.myName }}"