name: Workflow 1

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  read-config:
    uses: ./.github/workflows/read-config.yml

  first-job:
    name: First Job
    runs-on: ubuntu-latest
    needs: read-config

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Say Hi
        run: echo "Hi, I am the first step in the first job of the first workflow."
      
      - name: Use Config Variables
        run: |
          echo "Flutter version: $FLUTTER_VERSION"
          echo "Java version: $JAVA_VERSION"
          echo "Java distribution: $JAVA_DISTRIBUTION"
          echo "My name: $myName"
          
      - name: Show All Config Variables
        run: |
          echo "All config variables:"
          env | grep -E "FLUTTER_VERSION|JAVA_VERSION|JAVA_DISTRIBUTION|myName"