name: Workflow 1

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  read-config:
    uses: ./.github/workflows/read-config.yml

  first-job:
    name: First Job
    runs-on: ubuntu-latest
    needs: read-config
    steps:
      - name: Set Config Variables
        run: |
          echo "${{ needs.read-config.outputs.config }}" >> $GITHUB_ENV
      
      - name: Say Hi
        run: echo "Hi, I am the first step in the first job of the first workflow."
      
      - name: Use Config Variables
        run: |
          echo "Flutter version: ${{ env.FLUTTER_VERSION }}"
          echo "Java version: ${{ env.JAVA_VERSION }}"
          echo "Java distribution: ${{ env.JAVA_DISTRIBUTION }}"
          echo "My name: ${{ env.myName }}"
          
      - name: Show All Config Variables
        run: |
          echo "All config variables:"
          env | grep -E "$(yq e 'keys | .[]' ./.github/config.yml | paste -sd '|' -)"