name: Workflow 1

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  read-config:
    uses: ./.github/workflows/read-config.yml

  first-job:
    name: First Job
    runs-on: ubuntu-latest
    needs: read-config

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Use Config Variables
        run: |
          # Convert CONFIG output to environment variables
          echo "${{ needs.read-config.outputs.config }}" | while IFS='=' read -r key value; do
            echo "${key}=${value}" >> $GITHUB_ENV
          done

      - name: Show Config Variables
        run: |
          echo "Flutter version: $FLUTTER_VERSION"
          echo "Java version: $JAVA_VERSION"
          echo "Java distribution: $JAVA_DISTRIBUTION"
          echo "My name: $myName"