name: Workflow 1

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  read-config:
    uses: ./.github/workflows/read-config.yml

  first-job:
    name: First Job
    runs-on: ubuntu-latest
    needs: read-config

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Parse and Use Config Variables
        run: |
          # Read CONFIG variable from the previous job
          CONFIG="${{ needs.read-config.outputs.CONFIG }}"

          # Split config into lines and extract each key-value pair
          echo "$CONFIG" | tr ' ' '\n' | while IFS= read -r line; do
            key=$(echo "$line" | cut -d ' ' -f 1)
            value=$(echo "$line" | cut -d ' ' -f 2​⬤